version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./:/usr/share/nginx/html:ro
    depends_on:
      - htpasswd
  htpasswd:
    image: httpd:2.4
    entrypoint: ["htpasswd", "-Bbc", "/output/.htpasswd", "admin", "2301955@SIT.singaporetech.edu.sg"]
    volumes:
      - ./htpasswd:/output 
  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/home/git
  flask:
    image: python:3.11-slim
    container_name: flask
    working_dir: /app
    volumes:
      - ./:/app
    command: /bin/sh -c "pip install -r requirements.txt && python app.py"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
  
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:h2:mem:sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: